[build]
  # command now runs from the project root.
  command = "pip install -r requirements.txt"

  # The frontend files are in 'public'.
  publish = "public"

  # The serverless functions are in 'api'.
  functions = "api"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/app/:splat"
  status = 200