[build]
  # Base directory tells Netlify where to run the build command from.
  base = "api"

  # This command will now run inside the 'api' directory.
  command = "pip install -r requirements.txt"

  # Publish directory MUST now be relative to the 'base' directory.
  # We use '../public' to go one level up from 'api' and then into 'public'.
  publish = "../public"

  # Functions directory is also relative to the 'base' directory.
  functions = "."

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/app/:splat"
  status = 200