[build]
  publish = "public/"
  command = ""

[[redirects]]
  from = "/api/*"
  # ↓↓↓ 确认这里已经换成了您 Render 应用的真实地址！
  to = "https://sound-light-api-purr.onrender.com/api/:splat" 
  status = 200
  force = true 

[[redirects]]
  from = "/auth/*"
  # ↓↓↓ 确认这里已经换成了您 Render 应用的真实地址！
  to = "https://sound-light-api-purr.onrender.com/auth/:splat"
  status = 200
  force = true