"""Add AudioFile model

Revision ID: 33badef76f93
Revises: a6654b6f44f4
Create Date: 2025-07-20 01:30:35.306431

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33badef76f93'
down_revision = 'a6654b6f44f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audio_file',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=300), nullable=False),
    sa.Column('track_type', sa.String(length=50), nullable=False),
    sa.Column('is_global', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('filename', 'track_type', name='_filename_track_type_uc')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('is_admin',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('is_admin',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    op.drop_table('audio_file')
    # ### end Alembic commands ###
